import { Project, TechStack } from '@/types';

export const PROJECT_TECH_STACK: Record<Project, TechStack[]> = {
  [Project.CryptoErp]: [
    TechStack.NextJs,
    TechStack.React,
    TechStack.TypeScript,
    TechStack.Jotai,
    TechStack.Emotion,
    TechStack.TailwindCSS,
    TechStack.NextI18next,
  ],
  [Project.SoohoIoHomepage]: [
    TechStack.NextJs,
    TechStack.React,
    TechStack.TypeScript,
    TechStack.Jotai,
    TechStack.Emotion,
    TechStack.TailwindCSS,
    TechStack.NextI18next,
  ],
  [Project.TealswapV3]: [
    TechStack.NextJs,
    TechStack.React,
    TechStack.TypeScript,
    TechStack.Jotai,
    TechStack.Emotion,
    TechStack.TailwindCSS,
    TechStack.Wagmi,
    TechStack.Viem,
  ],
  [Project.Mitosis]: [TechStack.NextJs, TechStack.React, TechStack.TypeScript],
  [Project.VivaLeva]: [
    TechStack.NextJs,
    TechStack.React,
    TechStack.TypeScript,
    TechStack.Recoil,
    TechStack.Emotion,
    TechStack.TailwindCSS,
    TechStack.ReactQuery,
    TechStack.Ethers,
  ],
  [Project.PurpleBridge]: [
    TechStack.NextJs,
    TechStack.React,
    TechStack.TypeScript,
    TechStack.TailwindCSS,
    TechStack.ReactQuery,
    TechStack.Ethers,
  ],
  [Project.CashierestWeb]: [
    TechStack.NextJs,
    TechStack.React,
    TechStack.JavaScript,
    TechStack.Emotion,
    TechStack.Redux,
    TechStack.ReactQuery,
  ],
  [Project.CashierestMobile]: [
    TechStack.NextJs,
    TechStack.React,
    TechStack.JavaScript,
    TechStack.Emotion,
    TechStack.Redux,
  ],
  [Project.TodoListApp]: [
    TechStack.NextJs,
    TechStack.React,
    TechStack.TypeScript,
    TechStack.Emotion,
    TechStack.Recoil,
    TechStack.Firebase,
  ],
  [Project.PPGG]: [
    TechStack.NextJs,
    TechStack.React,
    TechStack.JavaScript,
    TechStack.Emotion,
    TechStack.Recoil,
    TechStack.MongoDB,
  ],
  [Project.FEInterview]: [
    TechStack.NextJs,
    TechStack.React,
    TechStack.JavaScript,
    TechStack.Emotion,
  ],
  [Project.Polypoli]: [
    TechStack.React,
    TechStack.JavaScript,
    TechStack.CSS,
    TechStack.Redux,
    TechStack.SpringBoot,
    TechStack.Java,
    TechStack.NodeJS,
    TechStack.MySQL,
    TechStack.AWS,
  ],
};
